repos:
  - repo: local

    hooks:
      - id: yapf
        name: yapf
        entry: yapf
        language: system
        types: [python]
        args: ['--style=.style', '--in-place']

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ['--config-file=.style']
        
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ['--config=setup.cfg']

